project:
  type: website
  render:
    - "*.qmd"

website:
  title: "QORE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: people.qmd
        text: People
      - href: join.qmd
      text: Join us

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    bibliography: references.bib
